# Generated by Django 4.0.1 on 2024-04-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypost',
            name='description',
        ),
        migrations.AddField(
            model_name='mypost',
            name='imageUrl',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='mypost',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
