# Generated by Django 4.0.1 on 2024-05-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_apis', '0002_remove_mypost_description_mypost_imageurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypost',
            name='detail',
            field=models.CharField(default='', max_length=100),
        ),
    ]
