# Generated by Django 4.0.1 on 2024-05-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_apis', '0003_mypost_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('imageUrl', models.URLField(default='')),
                ('detail', models.CharField(default='', max_length=100)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
