# Generated by Django 4.0.1 on 2024-05-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_apis', '0004_homepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepost',
            name='userUrl',
            field=models.URLField(default=''),
        ),
    ]
